# Site settings
title: kmarenov
email: kmarenov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Kirill Marenov.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kmarenov.github.io" # the base hostname & protocol for your site
twitter_username: kmarenov
github_username:  kmarenov

# Build settings
markdown: kramdown
